### ISSUE TITLE
[QA] Some assets on the environment overlaps the nametag

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1032]
### **Explorer Alpha build version:**
**0.3.383-g852675f1-main**

### **Issue Description:**

When walking around a populated scenes (lots of assets) in some ocations we can see that the nametag of the avatar gets behind the asset.

### **Steps to reproduce:**

  1. `/goto -55,66` pointing west
  2. Walk slowly, watching the road and observe the nametag

### **Expected behaviour:**
Environmental objects do not overlap the nametag.

### **Current behaviour:**
Nametag is being overlaped by some assets.

#### **Evidence:**

![image](https://github.com/decentraland/unity-explorer/assets/139157886/abd898f1-33f2-4c56-8a3b-776c575e1d02)

https://github.com/decentraland/unity-explorer/assets/139157886/f9b85380-d10c-44a4-8528-794d33474690

**Comment by QThund** [comment]
The problem here is the background of the nametag, which is a SpriteRenderer that uses the default Sprites/Default material, which does not write to the Depth buffer, so the depth tests of the other object are all passing and overwriting the pixels.

**Comment by QThund** [comment]
It is not possible to use materials for the background and text labels that render them after Transparent objects due to the material of the font does not allow to change the render queue (by modifying the TextMeshPro custom editor for the Distance Field shader we could expose that field in the inspector though). @GBirch33 proposed to use a Renderer Feature instead.
