### ISSUE TITLE
goerli: can't play emotes from scene files

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1078]
### **Issue Description:**

In Goerli Plaza Avatar animations (80, -1) animations should play when clicking on the cubes or the pile of snow, but currently no action is being triggered.

### **Steps to reproduce:**

  1. Go to (80,-1)
  2. Click the cubes or the pile of snow
  
### How to fix:

Scene emotes are GLB files that we need to download as asset bundles and process them as emotes.
We need to update the AssetBundleConverter and update how we deal with animation clips inside GLBs, but this will mean that every animation in scenes will need to be using Mecanim which is not ideal.

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/219ba9fb-159a-4bd4-8fe6-bffc9ac3b352

**Comment by Kinerius** [comment]
I've just added a `How to fix` section that briefly explains why this does not work yet

**Comment by mikhail-dcl** [comment]
Converting everything to Animator seems the only way to support everything properly. It also feels to be the right technical way as legacy animations are legacy and no longer supported. 

I spoke with Pato and the performance impact of having Animator on every object is not as high as it was before. 

I also checked the AnimatorHandlerSystem and the logic connected to Animation (which we want to replace with Animator) is fairly scoped. 

It also seems that including a second branch with Animator (for backward compatibility during the transition period) would be fairly isolated. Writing a new system for handling `Animator` instead of `Animation` is also an option.

But we will need to reconvert everything :grimacing:
