### ISSUE TITLE
goerli: it's not possible to pick up the beer mugs

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1086]
### **Explorer Alpha build version:**

- **0.3.402-g7a23dc7e-main**
- **v0.10.0**
- **v0.11.0**
- **v0.12.0**
- **v0.13.0**

### **Issue Description:**

`/goto (73,-7)` and get close to the beer dispenser. The highlight surrounding the item and the tooltip E to pick up will appear, but it's unresponsive.

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/e501f22a-35f9-41b1-850e-70bd85415390)

**Comment by lorux0** [comment]
This problem is a race condition. The scene asks for the `CrdtGetState`, but the first time it does not include the `PBPlayerIdentityData`, `PBAvatarBase` & `PBAvatarEquippedData`. This provokes the `getPlayer()` function to return `null`, so `currentPlayerId` is never initialized: https://github.com/decentraland/sdk7-goerli-plaza/blob/e70ff6dc4fba1984bb529e7c559f6148a070ba3f/beer-dispenser/src/modules/helpers.ts#L12

In order to fix this problem, we need these systems to write into the crdt before the scene starts to run:
- https://github.com/decentraland/unity-explorer/blob/ef921ff2beff4f14fe34a4bdf61f7ae34a14913a/Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WritePlayerIdentityDataSystem.cs#L39
- https://github.com/decentraland/unity-explorer/blob/ef921ff2beff4f14fe34a4bdf61f7ae34a14913a/Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WriteSDKAvatarBaseSystem.cs#L40
- https://github.com/decentraland/unity-explorer/blob/ef921ff2beff4f14fe34a4bdf61f7ae34a14913a/Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WriteAvatarEquippedDataSystem.cs#L48

This is where the scene starts, on which will trigger the request of the crdt state: https://github.com/decentraland/unity-explorer/blob/ef921ff2beff4f14fe34a4bdf61f7ae34a14913a/Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/ControlSceneUpdateLoopSystem.cs#L72


### One possible solution

`Profile` and `PlayerCRDTEntity` for our player should be passed upon the scene creation, and thus they will be available on the system's initialization step.


### My tests (with no success)

I've tried to manually add the `PlayerCRDTEntity` into the worlds, either global and the scene just like [PlayerCRDTEntitiesHandlerSystem](https://github.com/decentraland/unity-explorer/blob/ef921ff2beff4f14fe34a4bdf61f7ae34a14913a/Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerCRDTEntitiesHandlerSystem.cs#L52) does:

```
private void InjectMainPlayerCRDTEntity(SceneFacade sceneFacade)
{
    int crdtEntityId = SpecialEntitiesID.PLAYER_ENTITY;

    SceneEcsExecutor sceneEcsExecutor = sceneFacade.EcsExecutor;

    Entity sceneWorldEntity = sceneEcsExecutor.World.Create();
    var crdtEntity = new CRDTEntity(crdtEntityId);

    sceneEcsExecutor.World.Add(sceneWorldEntity, new PlayerCRDTEntity(crdtEntity, sceneFacade, sceneWorldEntity));

    globalWorld.Add(mainPlayerEntity, new PlayerCRDTEntity(crdtEntity, sceneFacade, sceneWorldEntity));
}
```

I've tried overriding the `Initialize()` method of the systems of the related systems, for example `WritePlayerIdentityDataSystem`:
```
public override void Initialize()
{
    CreatePlayerIdentityDataQuery(World, false);
}

protected override void Update(float t)
{
    CreatePlayerIdentityDataQuery(World, true);
    ...
}

[Query]
[None(typeof(DeleteEntityIntention))]
private void CreatePlayerIdentityData([Data] bool checkDirtyFlag, PlayerCRDTEntity playerCRDTEntity, Profile profile)
{
    if (checkDirtyFlag && !playerCRDTEntity.IsDirty) return;

    ecsToCRDTWriter.PutMessage<PBPlayerIdentityData, (string address, bool isGuest)>(static (pbComponent, data) =>
    {
        pbComponent.Address = data.address;
        pbComponent.IsGuest = data.isGuest;
    }, playerCRDTEntity.CRDTEntity, (profile.UserId, !profile.HasConnectedWeb3));
}
```

The problem is that the query never executes, seems the ecs context is not yet correct.

I've also tried on adding the scene to the cache before it runs, by inverting this calls [here](https://github.com/decentraland/unity-explorer/blob/ef921ff2beff4f14fe34a4bdf61f7ae34a14913a/Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/ControlSceneUpdateLoopSystem.cs#L80) so [this check](https://github.com/decentraland/unity-explorer/blob/ef921ff2beff4f14fe34a4bdf61f7ae34a14913a/Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerCRDTEntitiesHandlerSystem.cs#L54) does not fail and we can get the `PlayerCRDTEntity` created. Although it was also needed to add some frame delays so we provide enough time for the systems to run their queries.
