### ISSUE TITLE
goerli: clap-meter needle goes up too fast

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1116]
### **Explorer Alpha build version:**
**0.3.402-g7a23dc7e-main**
v.0.10.0

### **Issue Description:**

Goerli Plaza Clap-meter `(82,0`): in the old explorer, the needle goes up a little for each time I do the clap emote. On EA, it keeps going up for as long as I'm looping the clap emote. The idea is that this meter requires a whole crowd (or someone spam-clicking the clap). 

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/3b7f163e-4213-48ce-a180-b5f35cfe614a

**Comment by sandrade-dcl** [comment]
Hey @anicalbano, I've been testing both versions, old renderer and explorer alpha, and in the old renderer the needle also keeps going up for as long as we're looping the clap emote in the same way the current E@ does.

**OLD RENDERER:**

https://github.com/user-attachments/assets/7f1abc72-483b-4fcb-8dc7-fc19a6223608

In order to confirm it, I've also taken a look to the scene's code and, as far as I see in the implemented logic, it's only needed to reproduce 4 clap emotes to make the needle reach the max level.

![Image](https://github.com/user-attachments/assets/8c39aa7f-f90b-49c9-87ef-ba469722ed65)

I would say that the current Explorer Alpha behavior is correct. Could you please re-check it? Thanks!

**Comment by anicalbano** [comment]
It is correct! I'll close the ticket with the info. Thanks, Santi!
