### ISSUE TITLE
Road teleporting behavior seems invalid

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#1184]
### **Issue Description:**
Teleporting to a road always takes you to the corner of that road. so even if you teleport to the very end, you always end up at what I assume is the scenes spawn point.

### **Steps to reproduce:**

  1. Select any road and spawn along it
  2. Notice you always end up at the bottom left/spawn point of the road.

**Comment by sandrade-dcl** [comment]
This happens specially in the "Tram Line" roads that are scenes made by a lot of parcels but with only 1 spawn point configured.

Fore example, in this case we are pointing to the `0,30` coordinate, however in the details panel we see `0,12` as "location". This is because all the long street scene is configured with the single spawn point `0,12`.

![Image](https://github.com/decentraland/unity-explorer/assets/64659061/9037e2c4-6b4e-4161-b694-1aed6f39d7a9)

## Suggested solution
I don't think we should have to apply any specific logic for the specific scenes where this is happening and ignore the current spawn points sytem, but ask the Content Team about to modify the `json` configuration of these scenes in order to add several spawn points (instead of only one) so our system would find the nearest point and jump in to it. In this way, although we won't appear in the exact coordinate where we clicked in the map, we would appear very near of it.

cc/ @m3taphysics
