### ISSUE TITLE
[QA] 'Spawn Cube' Modal Overlaps with Map UI

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1353]
### **Explorer Alpha build version:**
v0.10.0

### **Issue Description:**
The 'Spawn Cube' modal overlaps with the map UI, causing interface issues and obstructing the map view.
The issue is more noticeable on Mac; it's much less severe on Windows.

### **Steps to reproduce:**

  1. `/goto 10,65`
  2. Observe that the 'Spawn Cube' modal overlaps with the map UI.
  3. `/goto 76,-8`
  4. `/goto 79,-8`
 

### **Expected behavior:**
<img width="1723" alt="Screenshot 2024-07-01 at 5 18 38 PM" src="https://github.com/decentraland/unity-explorer/assets/146741383/7e8df90d-385b-458a-aa1c-ad99ba26dea8">

### **Current behavior:**
<img width="686" alt="Screenshot 2024-07-01 at 5 22 48 PM" src="https://github.com/decentraland/unity-explorer/assets/146741383/32a4a167-5e53-47d0-af2a-852d1640aece">

![image (1)](https://github.com/decentraland/unity-explorer/assets/146741383/8f6d0c2c-b666-486a-9824-e6171f3371a0)
![Uploading Screenshot 2024-07-03 at 11.45.43 AM.png…]()

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by anicalbano** [comment]
The modal still overlaps the left pannel on v0.11.0
![image](https://github.com/decentraland/unity-explorer/assets/139157886/73f7f7dc-bbb7-4501-8893-d9e82c2636b8)

**Comment by sandrade-dcl** [comment]
This is not an issue really, the position of that UI is decided by the scene and it's exactly the same as in the old renderer. What is happening is that the scene's UI is overlapping our Unity's UI that now has a different design and size (for example the minimap).

Not sure what we should do in this case, but we should invoke SDK team in order to them to take into consideration the new Explorer Alpha UI sizes (I think there currently exist a series of "margin limitations" for avoiding developers overlap our UIs, right?).

cc/ @nearnshaw @pravusjif

**Comment by nearnshaw** [comment]
Yes, the Unity UI should ALWAYS appear in front of scene UIs, we should enforce that.
We can easily adjust the position of the UI on that scene, not a problem. But it's a lot more interesting that whenever this happens, that the scene's UI appears behind.

Otherwise for example you could block the map UI, and not let players leave your scene :p . Or even close the game :o

**Comment by sandrade-dcl** [comment]
Ok, I will force it to always appears behind the Unity's UI 👍
