### ISSUE TITLE
Goerli |  Avatar Swap: Issues with avatar visibility and animations in multiple scenes on Goerli

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1643]
### **Explorer Alpha build versions:**

- **v0.16.0**

### **Issue Description:**
In the 'Advanced-Avatar-Swap' scenes at coordinates (76, -7) and (76, -6), the original avatar remains visible, and sometimes disappears. The swapped avatar is only visible when jumping, and its animations do not match the player's movements. Additionally, in the 'Avatar-Swap' scene at coordinates (75, -7), there is a noticeable delay before the avatar swap is reflected.

### **STR:** 

1. Launch the explorer.
2. Use the command `/goto goerli`.
3. Navigate to the 'Advanced-Avatar-Swap' scenes at coordinates (76, -7) and (76, -6).
4. Observe the avatar swap behavior and check for animation mismatches.
5. Jump to see if the swapped avatar becomes visible.
6. Navigate to the 'Avatar-Swap' scene at coordinates (75, -7).
- Observe the time it takes for the avatar swap to be reflected.

### **Expected behaviour:**

1. Avatar swap should work seamlessly, with the swapped avatar immediately visible and properly animated according to the player's movements.
2. Avatar swap should be reflected without delays in all relevant scenes.

### **Current behaviour:**

1. In 'Advanced-Avatar-Swap' scenes:
- The original avatar remains visible or disappears.
- The swapped avatar is only visible when jumping.
- Animations do not match the player's movements.

2. In 'Avatar-Swap' scene:

- There is a delay before the avatar swap is reflected.
 

https://github.com/user-attachments/assets/a1b4854f-fa20-48dd-a2ce-9ee3a9c74263

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by sandrade-dcl** [comment]
This issue should be solved when we fix the issue #359 👍

**Comment by lorux0** [comment]
This issue is related to the mutex.

The problem is that the update of the [AvatarModifierAreaHandlerSystem](https://github.com/decentraland/unity-explorer/blob/7f466c89500a8499eede466d4b435026a618a260/Explorer/Assets/DCL/SDKComponents/AvatarModifierArea/Systems/AvatarModifierAreaHandlerSystem.cs#L37) is not executing, and therefore the component isn’t being processed, so the avatar isn’t hidden, leaving it duplicated as shown in the issue video. This only happens when multiple scenes are loading around it.

As far as I can tell, it’s because it doesn’t pass [this](https://github.com/decentraland/unity-explorer/blob/7f466c89500a8499eede466d4b435026a618a260/Explorer/Assets/Scripts/ECS/Groups/FixedUpdateThrottledGroup.cs#L41) check (if i disable it it always works). And this happens because allowed is always false since the `BeforeUpdate` isn’t executed, and that’s because it doesn’t pass [this mutex acquired check](https://github.com/decentraland/unity-explorer/blob/7f466c89500a8499eede466d4b435026a618a260/Explorer/Assets/Scripts/ECS/Groups/SyncedGroup.cs#L72). The system that should acquire the mutex is [LockECSSystem](https://github.com/decentraland/unity-explorer/blob/7f466c89500a8499eede466d4b435026a618a260/Explorer/Assets/Scripts/ECS/LifeCycle/Systems/LockECSSystem.cs#L26). The root issue seems to be that the mutex is adquired after the `BeforeUpdate`.
