### ISSUE TITLE
[QA] Nametag is jittery and detaching from the avatar

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1664]
### **Explorer Alpha build versions:**
v0.17.0 and older

### **Issue Description:**

When moving around, the nametag over the avatar starts shaking with a trembling movement and when runing it gets a little bit detached from the avatar.

### **STR:** 

  1. Move around, walk, jump and run while observing the nametag.
  
### **Expected behaviour:**
The nametag should be attached to the avatar movement

#### **Evidence:**

https://github.com/user-attachments/assets/8d097188-5f8c-4bcb-ad83-7d500cab9eaf

**Comment by QThund** [comment]
I suspect that it has to do with the order in which entities update every frame, which is not fixed. In one frame the position of the name tag is set before the avatar has moved, and in the next frame it is set after the avatar has moved so it "randomly" jitters due to in some frames it does not move at all. Forcing it to update its position after all avatars have moved solves the issue.
