### ISSUE TITLE
[QA] Emissive light too strong or missing in some wearables

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1725]
### **Explorer Alpha build versions:**
v0.20.0

### **Issue Description:** (As reported on slack)

Emissive light in some wearables is too strong and making the colors blown out.
In some other cases, the glow of wearables is missing or is lower than it should be.

Conclussion: the emissive light overworks in some wearables and is missing on others

My address to check with my wearables:
`0xd545B9E0A5F3638a5026d1914CC9b47ed16B5ae9`

#### **Evidence:**
https://drive.google.com/file/d/19q2snjXHVT5LZsOIJmHBD90fRqSOgSIe/view?usp=drive_link
https://drive.google.com/file/d/1LMBJgXZ5WaYAGKO0oHqR2K6AzUPcGYQ_/view?usp=drive_link
https://drive.google.com/file/d/1rHHjRWAAJEOFCuFHOjJZvJND0yaBzvuu/view?usp=sharing

https://github.com/user-attachments/assets/22dff065-15ef-4ec0-a9ba-eeffa463bd90

https://github.com/user-attachments/assets/4e97d2a6-1a17-400c-a9e6-7c5f88b34597

**Comment by GBirch33** [comment]
![image](https://github.com/user-attachments/assets/cff21a7e-160f-470e-80c4-c30b2474a146)
So the one of the left is Lit and the right is Toon.

This proves my theory that the values provided through Toon shader will produce the expect result. So I assume that old renderer has a different evaluate of emissive materials, which isn't PBR compliant whereas ours is, so changing the shader isn't a wise decision.

Further investigation is required, especially since Scene shader is in a similar/same situation.
