### ISSUE TITLE
[QA] OldGuyBBQ - Cannot access rooftop level

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1766]
### **Explorer Alpha build versions:**

- **v0.20.0**
- **v0.46.0**

### **Issue Description:**

On scene `/goto-97,-95` we can access a second floor and a rooftop level. Currently, the button to reach the rooftop is unresponsive.

### **STR:** 

  1.  `/goto-97,-95`
  2. Press the button of Party Portal
  3. At the next level, press the button with the arrow to access the rooftop

### **Expected behaviour:**
The player should go to the selected level

### **Current behaviour:**
The button is unresponsive

#### **Evidence:**

https://github.com/user-attachments/assets/ca7e8f62-b1e6-4ef2-995c-b2a44c182866

#### **Additional Notes:**

Notes by the user:
`From Unknower: looks like that button is being generated by the Virtual Land Manager dependency after the scene's initial load in. It's using the movePlayerTo() function, which works on another click event in the scene. That rooftop button is working in browser/old client but not new client it seems`

**Comment by olavra** [comment]
@Ludmilafantaniella can you please add evidence of what is the expected behavior in Explorer web?

**Comment by anicalbano** [comment]
The expected behavior is for the button to take you to the rooftop

https://github.com/user-attachments/assets/6ffa00c8-1e06-4a57-bd76-1be2809e8c37

**Comment by m3taphysics** [comment]
We fixed teleport to, lets review this again on main @anicalbano

**Comment by anicalbano** [comment]
> We fixed teleport to, lets review this again on main @anicalbano

On latest (checked 0.29.0) the button is still not working, doesn't take you to the rooftop by pressing it

**Comment by m3taphysics** [comment]
@fcolarich lets verify the function being called is actually the one we fixed and see if we can see why this specific case isn't working.

**Comment by fcolarich** [comment]
The button press Input IS being sent through the CRDT but there is no "move player to" command coming from the scene... so seems like something is broken there...
This scene mentions it uses something called **Virtual Land Manager dependency **...
Do we have any way to look at the scene source code?

**Comment by fcolarich** [comment]
This one is really tricky to debug, because the issue seems to be in the underlying use of an outside tool that "manages" these buttons and functionality. And seems that some functionality of that tool does not work properly with the new client.
We would need to see the source code of the scene to continue debugging it, but its a very case specific issue sadly. Ideally the creator can just update the scene and put a proper button with a proper move player to method in it and that's all.
But if we are really willing to invest the time, we need the scene source code to check why its failing to properly link the button with the method call.

**Comment by Juliendcl** [comment]
I talked to OldGuy who said we can close that ticket, he wants to revamp the all scene and will start working on it in a few days. Should the issue persist afterwards, he will reach out to us
