### ISSUE TITLE
On boarding scene - User is able to multiply the captcha letters on Mat's reward

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2042]
### **Explorer Alpha build versions:**
v0.25.42

### **Issue Description:**
User is able to multiply the captcha letters when closing and re-opening the captcha modal on Mat's reward 

### **STR:** 

  1. Open v0.25.42
  2. Go to /world cryptonico.dcl.eth
  3. Complete the first part of the On boarding 
  4. Talk to mat 
  5. Complete the quest 
  6. Validate that the reward appears on the screen 
  7. Instead of putting the captcha , try to ignore it by pressing the grey button
  8. Repeat step 7 again 
  9. Validate that multiple captchas appear on the captcha screen 

### **Expected behaviour:**
Mat's Reward captcha should be readable 

### **Current behaviour:**
Mat's reward captcha multiplies everytime the user presses the grey button instead of the pink one 

#### **Evidence:**

https://github.com/user-attachments/assets/c58648a9-3366-439a-9197-a910a8fce95b

#### **Additional Notes:**
Windows 11 pro 
16 GB RAM 

📂 Scene Repository
https://github.com/agustincarriso/dcl-sdk7-onboarding

**Comment by sandrade-dcl** [comment]
@DafGreco it seems it's a problem in the scene's code. I've tested it in the old unity-renderer (https://decentraland.org/play/?realm=cryptonico.dcl.eth) and it's happening exactly the same (see attached screenshot).

![Image](https://github.com/user-attachments/assets/cc523c82-2eaf-4727-bee2-1921137bc438)

In fact, in the first conversation with Bezier, if you try to do the same with its captcha, it works fine.

Please move the issue to the corresponding developers of this scene in order to them to take a look to it.

**Comment by DafGreco** [comment]
Fix deployed on world onboardingdcl and verified 

https://github.com/user-attachments/assets/5cbc3b87-82c2-4323-9852-8ef393b24124
