### ISSUE TITLE
Profile requests are very high

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#2142]
### **Explorer Alpha build versions:**
We need to verify the number of profile requests makes sense, when we tested explorer alpha internally we seemed to have many requests despite there being only 20-30 users.

We did change wearables and play emotes quite a few times. So this number may be normal.

![image](https://github.com/user-attachments/assets/61719187-e9d6-497c-897c-c72f3ecc4888)

**Comment by sandrade-dcl** [comment]
Effectively I have detected a huge amount of duplicated requests to the Profile each time any of the other avatars changes something in his profile: Backpack, Passport, etc.

![Image](https://github.com/user-attachments/assets/5a3919a7-9561-4529-a47a-63f02e8a3c34)

In order to avoid this, I'm gonna try to detect all the duplicated in each bunch of downloads and only send it once.
