### ISSUE TITLE
[QA] 'Profile Pro' Badge Delay

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2238]
### **Explorer Alpha build versions:**

- **v0.29.0**
- **v0.30.0**

### **Issue Description:**
The 'Profile Pro' badge, awarded the first time a user updates their profile, takes time to appear. Users must close and reopen the explorer to see the badge reflected in their passport.

### **STR:** 

1. Launch the explorer with a new account.
2. Make a change to your profile.
3. Check the passport for the 'Profile Pro' badge.

### ❌ Actual Result
The 'Profile Pro' badge does not appear immediately. Users must close and reopen the explorer to see it.
![image](https://github.com/user-attachments/assets/4bc32f4a-30a2-4218-b484-bc685ce333a6)

### ✅ Expected Result
The 'Profile Pro' badge should be awarded immediately and visible in the passport without needing to restart the explorer.
![image](https://github.com/user-attachments/assets/2bd26745-bed3-41b0-8674-897147857240)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by sandrade-dcl** [comment]
@Ludmilafantaniella I'm not able to repeoduce this issue. I have requested to Alejo to remove the "Profile Pro" badge from my profile in order to do the obtaining process again and, once I modified my profile from the Passport, after waiting some seconds (this time depends on the back-end), I opnened my Passport and I saw the badge there without having to close and re-open the app.

![Image](https://github.com/user-attachments/assets/6c584503-bb78-4730-ab5d-d921f495d89f)

Could you please re-check it?

**Comment by sandrade-dcl** [comment]
It seems there is being problems with badges like this one that comes from Catalyst.
I have assigned the ticket to Alejo.
More info [here](https://decentralandteam.slack.com/archives/C0784NFC7QV/p1728394535195809).
