### ISSUE TITLE
[QA] Goerli | Beer Dispenser Unresponsive (73,-7)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2336]
### **Explorer Alpha build versions:**

- **v0.32.0**

### **Issue Description:**
In the Goerli scene at coordinates (73,-7), the beer dispenser is unresponsive. While the highlight surrounding the mug and the tooltip "E to pick up" appear when approaching the dispenser, it is not possible to pick up the mug or dispense beer.

### **STR:** 

1. Go to the coordinates (73,-7) in Goerli.
2. Approach the beer dispenser.
3. Observe that the highlight appears and the tooltip "E to pick up" shows up.
4. Press "E" to pick up the mug or dispense beer.

### ❌ Actual Result
The item remains unresponsive, and the player is unable to pick up the mug or use the beer dispenser.

https://github.com/user-attachments/assets/80fd8bda-044b-4834-81b5-25cbcbfb2803

### ✅ Expected Result
The player should be able to interact with the beer dispenser, pick up the mug, and dispense beer when prompted.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by mikhail-dcl** [comment]
Most likely it's because of recent multiplayer changes: player data is no longer available on start. So the scene should have been refactored. It was the agreement with @gonpombo8

**Comment by aixaCode** [comment]
@nearnshaw Would you be able to take a look at the scene?

**Comment by nearnshaw** [comment]
@mikhail-dcl  could you please provide some more info about what changed and why, and who made the call?

it seems like that change is likely a big step backwards in usability, and potentially breaking for many existing scenes.

In this scene in particular, I believe a workaround should be possible. When picking up a mug, we attach the mug to the player. The player's id is obtained via this snippet, which runs when the scene loads:

```ts
void executeTask(async () => {
  const user = getPlayer()
  if (!user) return
  currentPlayerId = user.userId
})
```

I assume the scene stopped working properly because at the time of running this, the player data is not yet available.
I can for sure make modifications for the scene so that this info is only required when needed and not at the start, my worry is that there'll be other scenes where this information will be needed at the start of the scene.

For example, any of the halloween/xmas quests we did required loading the scene differently depending on who the player is and what they did in the past, checking in a 3rd party server. In those cases the scene should be able to send a request to ask the server that includes the player's id from the very start.

**Comment by nearnshaw** [comment]
I have done a PR that I can confirm fixes the beer scene

https://github.com/decentraland/sdk7-goerli-plaza/pull/238

I do think that this breaking change in the scene lifecycle has potentially broken other scenes, a few cases came up today that I suspect could be related to this. Specifically Angzaar Outpost scene, and possibly also all scenes that use the Virtual Land Manager tool (like Dollhouse).
