### ISSUE TITLE
[QA] Minigames | Daily Mission completion not triggered in-game for certain minigames

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2447]
### **Explorer Alpha build versions:**

- **v0.35.0**

### **Issue Description:**
In the minigames Mosaic Mania, Recall Rush, and Memory Grid, the completion of the Daily Mission is not registered until the player exits the minigame. In other minigames, like Color Pop, Tower of Hanoi, Word Search, 2048, and Liquid Labyrinth, the mission completion is triggered in real-time, opening the Daily Mission modal with a checkmark upon reaching the objective.

### **STR:** 

1. Start a Daily Mission involving Mosaic Mania, Recall Rush, or Memory Grid.
2. Reach the objective.
3. Observe that the Daily Mission modal does not open with a checkmark in-game.
4. Exit the minigame and notice that the completion is only registered after exiting.

### ❌ Actual Result
Mission completion is not registered until the player exits the minigame.

![memoryGrid](https://github.com/user-attachments/assets/cf6f573e-6321-4c48-8236-6a60ff573622)

https://github.com/user-attachments/assets/8a21c6eb-cbe6-4f24-8fc7-4830e9057808

https://github.com/user-attachments/assets/ea6ae205-e061-48a0-80d0-4afd6e9b5040

### ✅ Expected Result
Mission completion should be triggered in real-time upon reaching the objective, opening the Daily Mission modal with a checkmark without needing to exit the game.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by gonpombo8** [comment]
https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1731607266314159
Here is a thread about this issue and how to repro.


More context:
There is a race condition that sometimes you are disconnected from the island and it stops sending positions to archipelago.
And because it stops sending positions, you are connected forever to a island that is not the island that you should be connected. Archipelago cant tell you which is the correct island because the client stopped sending position messages
[12:17](https://decentralandteam.slack.com/archives/D04CWSNUTU6/p1732029464109769)
and because of that, you are not visible here: https://archipelago-ea-stats.decentraland.org/comms/peers. That is the enpdoint that we are using to validate the user is inside DCL

**Comment by m3taphysics** [comment]
Fixed with: https://github.com/decentraland/unity-explorer/issues/2686
