### ISSUE TITLE
Error: syncEntity failed because the id provided is already in use

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-explorer#671]
ERROR SYNCENTITY - syncEntity
Exception: ScriptEngineException: Error: syncEntity failed because the id provided is already in use from scene 67_67

**Comment by pravusjif** [comment]
Since that scene error doesn't happen in the old renderer, Gon suggested there's the possibility that in the Explorer Alpha we are calling the same instruction/function twice (thus trying to apply the same change to the same syncEntity twice,and triggering that error), something we'll have to look into

**Comment by NickKhalow** [comment]
Status: waiting for an update from other team

**Comment by m3taphysics** [comment]
Lets try reproduce this in the group test.
